apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fpm
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mediawiki.port }}
      targetPort: {{ .Values.mediawiki.port }}
  selector:
    app: {{ .Release.Name }}-fpm