apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apache
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.apache.port }}
      targetPort: 80
  selector:
    app: {{ .Release.Name }}-apache