{{- $svc := .Release.Name }}
{{- range .Values.tcpEntryPoints }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $svc }}-{{ .entryPoint }}
spec:
  entryPoints:
    - {{ .entryPoint }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ $svc }}
          port: {{ .servicePort }}
  tls:
    passthrough: {{ .tlsPassthrough | default true }}
---
{{- end }}
