{{- range .Values.doipConfig.ports }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  entryPoints:
    - {{ .name }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ $.Release.Name }}
          port: {{ .port }}
  tls:
    passthrough: {{ .tlsPassthrough | default true }}
---
{{- end }}
