image:
  repository: ghcr.io/mardi4nfdi/mardi_fdo_server
  tag: latest
  pullPolicy: Always

replicas: 1

servicePort: 80
containerPort: 8000

ingress:
  subdomain: "fdo"

resources:
  requests:
    memory: "128Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"