image:
  repository: ghcr.io/mardi4nfdi/mardi_doip_server
  tag: latest
  pullPolicy: Always

replicas: 1

servicePort: 80
containerPort: 80
  
doipConfig:
  ports:
    - name: doip-tls1
      port: 3567
      tlsPassthrough: true
    - name: doip-tls2
      port: 3568
      tlsPassthrough: true

ingress:
  subdomain: "doip"

resources:
  requests:
    memory: "128Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"
