image:
  repository: ghcr.io/mardi4nfdi/mardi_doip_server
  tag: latest
  pullPolicy: Always

replicas: 1

global:
  baseDomain: example.com

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: doip-tcp
      port: 3567
      targetPort: 3567
    - name: doip-tls
      port: 3568
      targetPort: 3568

ingress:
  subdomain: "doip"

tcpEntryPoints:
  - entryPoint: doip-tls1
    servicePort: 3567
    tlsPassthrough: true
  - entryPoint: doip-tls2
    servicePort: 3568
    tlsPassthrough: true

resources:
  requests:
    memory: "128Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"
