kafka:
  image:
    repository: apache/kafka
    tag: 3.7.0
  storage: 20Gi
  resources:
    requests:
      cpu: "250m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  heapOpts: "-Xmx512M -Xms512M"

eventgate:
  image:
    repository: docker-registry.wikimedia.org/wikimedia/eventgate-wikimedia
    tag: ffd68c0de41e3395e2f8ba9422fbe8824c2a49ff
  numWorkers: 1
  loggingLevel: "info"
  testMode: false
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

eventstreams:
  image:
    repository: docker-registry.wikimedia.org/repos/data-engineering/eventstreams
    tag: v0.9.0
  numWorkers: 1
  loggingLevel: "info"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

secrets: "mediawiki-events-secrets"