apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-matomo
spec:
  chart:
    spec:
      version: "0.1.1"
  values:
    backup:
      name: "backup-matomo"
      schedule: "0 6 * * *"
      bucket: "mardi"
      prefix: "production/matomo"
      endpoint: "hsm-test-09.zib.de:9001"
      region: "us-east-1"
    storage:
      size: 10Gi
    metrics:
      enabled: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m" 
        memory: "1Gi"