apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opensearch
spec:
  chart:
    spec:
      version: "0.1.0"
  values:
    replicas: 1
    storage:
      size: 200Gi
    resources:
      requests:
        memory: "12Gi"
        cpu: "2"
      limits:
        memory: "18Gi"
        cpu: "8"
    javaOpts: "-Xms14g -Xmx14g"
    