apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: flink-main
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: 
            - "/opt/flink/bin/flink"
            - "run"
            - "--class"
            - "org.wikidata.query.rdf.updater.UpdaterJob"
            - "/usr/local/lib/python3.9/dist-packages/pyflink/streaming-updater-producer.jar"
            - "/etc/flink/conf/rdf-updater.properties"
          env:
            - name: DISABLE_JEMALLOC
              value: "true"
            - name: FLINK_PROPERTIES
              value: |
                jobmanager.rpc.address: localhost
                taskmanager.numberOfTaskSlots: 1
                jobmanager.memory.process.size: {{ .Values.flink.jobManagerMemory }}
                taskmanager.memory.process.size: {{ .Values.flink.taskManagerMemory }}
                taskmanager.state.latency_tracking.enabled: true
          ports:
            - containerPort: 8081 # Dashboard
            - containerPort: 6123 # RPC
          volumeMounts:
            - name: config-volume
              mountPath: /etc/flink/conf
            - name: checkpoint-storage
              mountPath: /opt/flink/checkpoints
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
        - name: checkpoint-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-checkpoints