image:
  repository: docker-registry.wikimedia.org/repos/search-platform/flink-rdf-streaming-updater
  tag: flink-1.17.1-rdf-0.3.154
  pullPolicy: IfNotPresent

flink:
  jobManagerMemory: "1024m"
  taskManagerMemory: "2048m"
  parallelism: 1
  checkpointInterval: 60000
  logLevel: "INFO"

config:
  kafkaBootstrap: "kafka-0.kafka"
  wikiInternalUrl: "http://wikibase-apache"
  eventStreamConfigUrl: "http://eventstreams"
  schemaBaseUrl: "http://schema-registry"
  inputPageChangeStream: "mediawiki.page_change.v1"
  outputTopicPrefix: "mardi."

resources:
  requests:
    cpu: "500m"
    memory: "1.5Gi"
  limits:
    cpu: "1000m"
    memory: "2.5Gi"