apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: change-propagation
  namespace: staging
spec:
  chart:
    spec:
      version: "0.1.1"
  values:
    mediawiki:
      host: http://staging-wikibase-apache


