image:
  repository: docker-registry.wikimedia.org/repos/data-engineering/eventgate-wikimedia
  tag: v1.27.0
numWorkers: 1
loggingLevel: "info"
testMode: false
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"