# This user is created manually in the qlever-ui container
# Credentials are stored here for documentation

apiVersion: v1
kind: Secret
metadata:
  name: qlever-secrets
type: Opaque
data:
  QLEVER_UI_USER: <base64-encoded-qlever-ui-user>
  QLEVER_UI_PASSWORD: <base64-encoded-qlever-ui-password>