apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventgate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventgate
  template:
    metadata:
      labels:
        app: eventgate
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: config-volume
          configMap:
            name: eventgate-config      
      containers:
        - name: eventgate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: CONFIG_FILE
              value: "/srv/service/config.yaml"
            - name: NODE_PATH
              value: "/srv/service/node_modules/@wikimedia"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
          ports:
            - containerPort: 8192
          volumeMounts:
            - name: config-volume
              mountPath: /srv/service/config.yaml
              subPath: config.yaml
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}