apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: askmardi
spec:
  chart:
    spec:
      version: 0.1.0
  values:
    qdrant:
      url: "http://qdrant:6333"
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "3"
