apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/schema-registry
patches:
  - path: values-staging.yaml
    target:
      kind: HelmRelease
      name: schema-registry