apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-key
  namespace: staging
type: Opaque
data:
  bouncer-key: ENC[AES256_GCM,data:6kx3mkC16FiDmfZMWdo0DlSMxByoH16s7Y7hWmzFNWh6RudCpakrc9L8Txl6c0ts2n2mqbeSwv+ZYePe,iv:aloKcwtPpi0Tro/r1w4hrykmEBU9m3WlyE4pj9Mfx40=,tag:kSNcNUC1Uor1Hd2jLop4uQ==,type:str]
sops:
  lastmodified: "2025-11-21T14:43:39Z"
  mac: ENC[AES256_GCM,data:Wkc/Mq65buQcSwrrMyq63Vui7ixmjVQ55bTojbN3Clra0pfHPvjdQPgoa05fh+317p1/CL4ISXnY7m8eC78rtHt/q93ZwN4G8PdjDX94pMkVZMT8i9sNyR193N7c3i9GwMTwIyWw2D9FljlHivxyMel0YrjCOMVoeJdQ+ew9E8c=,iv:hxK1/BCkdAOLeBpW+LR7gA4C7NpsFZ3EdPJh3rjoUyA=,tag:cqCa1URWyzvQpGpa260lKQ==,type:str]
  pgp:
    - created_at: "2025-11-21T14:43:39Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5ARAAzXEzsJwz1YPKCCHR34ysLu8/Kzf5zktvvsEgJbs6Fpuc
        m77cPHh7Dz52Bzo0yNiWRdxahpCWE6X5YvK8hC0wrve0KLSuVZg4TQBwhm3i/q5Q
        bMsqfDmAfpvGGxsBZweT0BsEygdfdjhT6YB3DV1rp6OxlzL43+ivphM5fJybpMwr
        dITPCBN+ReYDtUGdJQYREQm3NdmRb3qNzL/u4MSIMtoavslEe9xHe8EFDBF5NfJ5
        8J8S/lI47a6z2HZLSDSW2y57pmLZSo5zRQLj+4ZkBAaHZoibeKe9ZDAwgyKTM993
        fuxofED1cSIasY/uFpF79bq+yCQasb3g2N1KLCBc4IsDT3IrLgWq9VKdZQLmJCRq
        rBYEKaqyARa7Xm4U+MzceFFgx2C91DSHit33f9j2/KwJWb234ecRpyGiO5FbHSPY
        gcawkmsVp8nADC3exajn+6ZEWBo984nVFeAM4mJuAJpeL74sEmIb3dLHlJOuO4JO
        vnvUJRaBYLa3fy3710NwRpQVKpSqNK+/r4cdF4x0EgNQqO5piDyA8E2WA167Gaie
        Zxz43RLT7U5KzU+GAnp+MLU+3ozR+c5EDWK19cAR3dhZBM5pGua9XP3OSZJ37Jf5
        WaS7Q+VccVGn5BRnIKbLua8MaTmeKebDPfiMTaN1l1TCY3HrPkTvc2/HwfsXljjS
        XAFL4LtmdnD9eg/vckSxXJSB80ZJv12tntvaj8QrQi7hLAvxgl569onvZevv+2rH
        stBeR1cxLMaR+qxsvtsdwh7na2ty4+jdSPg+sfs1jLluQeBQjU2VoIevbtpp
        =l/we
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
