apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-key
  namespace: staging
type: Opaque
data:
  bouncer-key: ENC[AES256_GCM,data:jzflqYaX/8gvkafnm+dK3SbA83IlE+9alimeQxBRiql3ZLS8ZKE6D3FPQf+13+PARgBdBqyPhDEf+9bR,iv:3TBIpw9ANqNPXOnud4oRzG8Dm1GRpN4SjvGVMFxHHPI=,tag:6cHYgJyVU6xX1PKe3SF9ow==,type:str]
sops:
  lastmodified: "2025-11-20T13:16:30Z"
  mac: ENC[AES256_GCM,data:xk4VuHOOO0QIV3yvC+TjjOwQ2qzbNLjGXEfToY1mXno1zdOQm4Sbi3Hp5nijey8meHxF4IfHYnHh4xvJfjtSUoO6Ay3DMyMchOiK2M6DqdzUgjQIHNtYE7ddigZrcmb28mZ0nWus/+ACq7WfPNTCz1vXKNf3a14QUeXNCmW/6Hg=,iv:v6wLu8NGfXXwMzldXAw8mbDuM1PGXnA8sRKD++HIj2c=,tag:1EJyihf3EQXvEA/WixJbiA==,type:str]
  pgp:
    - created_at: "2025-11-20T13:16:30Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA90tSATCInn5AQ/9Gxx96EzjBljn9uxydHccuny9yGiAQG5Gep0ommdhffyT
        GzL5PdHSUHmuXCXAVy5U+oaJ1GxMlwHHHhaEPPbRmQzZk5wyjEsM/UI/yF7vFBcE
        f9m34kKjs7jpcknZQ6PyRPBHpltIvsd+UPQAKMadv7VPNxcMtUDmA4U15JX9vnRV
        Pgfthtp0pU4YJjLS5k8XC9SFdoksxpaHIk+npFcnmJz6d+jlcNzxD8HGu+h3gVi+
        aRr/j3r/4QoxwWlmFYJni9Tj8Or6hhE1DL2HsnWp99G8bn0Ewz2T5iXERitX4Lk8
        rX9ZttIqgh+hWTJdYAzbLCealhvKC5fQWhszkkRpZFBcJT+TdqXmTihV/yQArGIU
        BpMTLK/RouzUi0cYuKyfzDQh2u9gfmxOCQKGHwrf7nbpgUG77JLt3g8bTqXHrj9e
        s5X1KVPpTHT12TNG/FusfwXf8PaxjFdXOD4AY/s/o9WSghnwqFoOmde9eOtVO+1a
        iQZvbnxwOKb4V19NPKGvFL6HGE6L0qOrenpUktExza9N9yUR4lAfTs7JTFUYd0rW
        mUKNovf9nW6awwo3c8PrKtmBCQ2+wtcdEdm3oMX//MXMi/kFmCz5x4t7MAbF3ySU
        JAbzF2SJEE99tbqlLZt1jFSJa2Bm1xu0PzIbhOvmH3cBHRajZUZv8r1uQvppu0vS
        XgE60krwgiawsPY7eqv7AHFC8FlLGXoXwhNZ5WyGNX2i2bkM2y9IujZpE+FWKF0m
        RsgyN1ovlSoFZcBJk4vkg0rWnFrEqYGqnJ7ani01aIck+M8Jh/uxfTGzIM62LS4=
        =d/AT
        -----END PGP MESSAGE-----
      fp: BE155DFF5AD65EA97520D7E6B003A490455B332D
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
