apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/qlever
namePrefix: staging-
namespace: staging
patches:
  - path: values-staging.yaml
    target:
      kind: HelmRelease
      name: qlever