apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: staging-qlever
  namespace: staging
spec:
  chart:
    spec:
      version: "0.1.5"
  values:
    qlever:
      image:
        repository: adfreiburg/qlever
        tag: commit-7ec91f8
      port: 7019
      cmdString: "qlever start --run-in-foreground"
    ingress:
      enabled: true
    