apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/rdf-streaming-updater
patches:
  - path: values-staging.yaml
    target:
      kind: HelmRelease
      name: rdf-streaming-updater