apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rdf-streaming-updater
  namespace: staging
spec:
  chart:
    spec:
      version: "0.1.21"
  values:
    config:
      wikiInternalUrl: "http://staging-wikibase-apache"
    flink:
      logLevel: "DEBUG"