apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rdf-streaming-updater
  namespace: staging
spec:
  chart:
    spec:
      version: "0.1.19"
  values:
    config:
      wikiInternalUrl: "http://staging-wikibase-apache"
      inputPageChangeStream: "mardi.mediawiki.page_change.v1"
    flink:
      logLevel: "DEBUG"