apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-propagation
  labels:
    app: change-propagation
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: change-propagation
  template:
    metadata:
      labels:
        app: change-propagation
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: change-propagation
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-c"
            - "/etc/change-propagation/config.yaml"
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/change-propagation
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /_info
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /_info
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: config
          configMap:
            name: change-propagation-config