apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.subdomain }}.{{ .Values.global.baseDomain }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-api
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.api.servicePort }}
  tls:
    secretName: {{ .Release.Name }}-tls