apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  selector:
    app: {{ .Release.Name }}-api
  type: ClusterIP
  ports:
  - port: {{ .Values.api.servicePort }}
    targetPort: {{ .Values.api.containerPort }}