apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: staging-doip
  namespace: staging
spec:
  chart:
    spec:
      version: "0.1.3"
  values:
    lakefs:
      url: "lake-bioinfmed.zib.de"
      repo: "sandbox"

