{{- if .Values.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-db-tls
spec:
  secretName: {{ .Release.Name }}-db-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.subdomain }}-db.{{ .Values.global.baseDomain }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
{{- end }}