apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  selector:
    app: {{ .Release.Name }}-ui