apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - mariadb.yaml
  - traefik.yaml
  - portainer.yaml
  - bitnami-redis.yaml
  - bitnami-memcached.yaml
  - jetstack.yaml
  - varnish.yaml
  - prefect.yaml
  - crowdsec.yaml