apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/kafka
  - secrets.yaml
patches:
  - path: values-staging.yaml
    target:
      kind: HelmRelease
      name: kafka